config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "porcs#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :porcs, only: [:index, :new, :create, :show, :edit, :update, :gestion] do
    get "gestion", to: "porcs#gestion"
    resources :prisuttus, only: [:new, :create, :edit, :update]
    resources :lonzus, only: [:new, :create, :edit, :update]
    resources :coppas, only: [:new, :create, :edit, :update]
  end

  resources :abattages, except: [:index, :update] do
    get "edit_produits", to: "abattages#edit_produits"
    get "edit_coppa", to: "abattages#edit_coppa"
    get "edit_lonzu", to: "abattages#edit_lonzu"
    get "edit_prisuttu", to: "abattages#edit_prisuttu"
    get "/dashboard", to: "abattages#dashboard"
    get "download", to: "abattages#download"
    get "preview", to: "abattages#preview"
    patch "update_abattage", to: "abattages#update_abattage", as: :update_abattage
    patch "/update_production", to: "abattages#update_production", as: :update_production
    patch "/update_produits", to: "abattages#update_produits", as: :update_produits
    patch "/update_coppa", to: "abattages#update_coppa", as: :update_coppa
    patch "/update_lonzu", to: "abattages#update_lonzu", as: :update_lonzu
    patch "/update_prisuttu", to: "abattages#update_prisuttu", as: :update_prisuttu
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_head_bar.html.erb
<div class="head-bar">
  <h1><%= link_to "DigiNustrale", porcs_path %></h1>

  <div class="info-head-bar">
    <% if current_user.nil? %>
      <span>Bienvenue !</span>
    <% else %>
      <span>Bonjour, <%= current_user.prénom %></span>
      <%= link_to destroy_user_session_path, data: { turbo_method: :delete, turbo_action: "replace", turbo_frame: "user-menu" } do %>
        <i class="fa-solid fa-right-from-bracket"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-container">
  <div class="option-bar">
    <div class="option-left">
      <p class="active" data-grid-target="button" data-action="click->grid#toggle">MON CHEPTEL</p>
      <p data-grid-target="button" data-action="click->grid#toggle">MES LOTS</p>
      <span class="active-indicator" data-grid-target="bar"> </span>
    </div>

    <div class="option-right">
      <div class="search active" data-grid-target="form">
        <form action="porcs" data-turbo-method="get">
          <input type="text" placeholder="N° IPG" name="ipg" value="<%= @ipg %>" required>
          <button type="submit"><i class="fas fa-search"></i></button>
        </form>
      </div>
      <div class="search" data-grid-target="form">
        <form action="porcs" data-turbo-method="get">
          <input type="text" placeholder="N° LOT" name="lot" value="<%= @lot %>" required>
          <button type="submit"><i class="fas fa-search"></i></button>
        </form>
      </div>

      <%= link_to new_porc_path, class: "button-custom" do %>
        <i class="fa-solid fa-plus"></i>&nbsp; AJOUTER UN ANIMAL
      <% end %>
      <%= link_to new_abattage_path, class: "button-custom", data: { turbo: "false" } do %>
        <i class="fa-sharp fa-solid fa-share"></i>&nbsp; ABATTAGE
      <% end %>
    </div>
  </div>
</div>