config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "porcs#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :porcs, only: [:index, :new, :create, :show, :edit, :update, :gestion] do
    get "gestion", to: "porcs#gestion"
    resources :prisuttus, only: [:new, :create, :edit, :update]
    resources :lonzus, only: [:new, :create, :edit, :update]
    resources :coppas, only: [:new, :create, :edit, :update]
  end

  resources :abattages, except: [:index, :update] do
    get "edit_produits", to: "abattages#edit_produits"
    get "edit_coppa", to: "abattages#edit_coppa"
    get "edit_lonzu", to: "abattages#edit_lonzu"
    get "edit_prisuttu", to: "abattages#edit_prisuttu"
    get "/dashboard", to: "abattages#dashboard"
    get "download", to: "abattages#download"
    get "preview", to: "abattages#preview"
    patch "update_abattage", to: "abattages#update_abattage", as: :update_abattage
    patch "/update_production", to: "abattages#update_production", as: :update_production
    patch "/update_produits", to: "abattages#update_produits", as: :update_produits
    patch "/update_coppa", to: "abattages#update_coppa", as: :update_coppa
    patch "/update_lonzu", to: "abattages#update_lonzu", as: :update_lonzu
    patch "/update_prisuttu", to: "abattages#update_prisuttu", as: :update_prisuttu
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/abattage.rb
class Abattage < ApplicationRecord
  has_many :porcs
  validates :numéro_lot, :date, :lieu, presence: true
  ABATTOIRS = %w(Cuttoli Bastelica Cozzano Ponte\ Leccia)
  validates :lieu, inclusion: {in: ABATTOIRS}
end

app/controllers/abattages_controller.rb
class AbattagesController < ApplicationController
  before_action :set_abattage, only: [:show, :edit]
  before_action :set_abattage_id, only: [:edit_produits, :update_abattage, :update_production, :download]

  def new
    @abattage = Abattage.new
    @porcs = Porc.where(décès: false, abattu: false)
  end

  def create
    @abattage = Abattage.new(abattage_params)
    if @abattage.save!
      porc_ids = params[:porc_ids].split(',')

      @porcs = Porc.where(id: porc_ids)
      @porcs.each do |porc|
        porc.update!(abattage: @abattage)
        porc.update!(abattu: true)
      end
      redirect_to abattage_path(@abattage)
    else
      render :new
    end
  end

  def show
    porcs_abattage = @abattage.porcs.flat_map {|porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))

    coppas_with_weight = @porcs.map(&:coppa).select do |coppa|
      coppa&.poids&.positive?
    end
    @coppa_temoin = coppas_with_weight.first

    lonzus_with_weight = @porcs.map(&:lonzu).select do |lonzu|
      lonzu&.poids&.positive?
    end
    @lonzu_temoin = lonzus_with_weight.first

    prisuttus_with_weight = @porcs.map(&:prisuttu).select do |prisuttu|
      prisuttu&.poids&.positive?
    end
    @prisuttu_temoin = prisuttus_with_weight.first

    @etape_un_rempli = etape_un_rempli?(@abattage.porcs)
    @etape_deux_rempli = etape_deux_rempli?(@abattage.porcs)
  end

  def edit
    porcs_abattage = @abattage.porcs.flat_map {|porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))
  end

  def edit_produits
    @abattage = Abattage.find(params[:abattage_id])
    porcs_abattage = @abattage.porcs.flat_map {|porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))
  end

  def edit_lonzu
    @abattage = Abattage.find(params[:abattage_id])
    porcs_abattage = @abattage.porcs.flat_map {|porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))
    lonzus_with_weight = @porcs.map(&:lonzu).select do |lonzu|
      lonzu.poids&.positive?
    end
    @lonzu_temoin = lonzus_with_weight.first
  end

  def edit_coppa
    @abattage = Abattage.find(params[:abattage_id])
    porcs_abattage = @abattage.porcs.flat_map {|porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))

    coppas_with_weight = @porcs.map(&:coppa).select do |coppa|
      coppa.poids&.positive?
    end
    @coppa_temoin = coppas_with_weight.first
  end

  def edit_prisuttu
    @abattage = Abattage.find(params[:abattage_id])
    porcs_abattage = @abattage.porcs.flat_map {|porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))

    prisuttus_with_weight = @porcs.map(&:prisuttu).select do |prisuttu|
      prisuttu.poids&.positive?
    end
    @prisuttu_temoin = prisuttus_with_weight.first
  end

  def update_abattage
    porcs_abattage = @abattage.porcs.flat_map { |porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))
    count = @porcs.count
    counter = 0
    count.times do
      porc = Porc.find(params[counter.to_s][:id])
      porc.update(ph: params[counter.to_s][:ph],
                  epaisseur_lard: params[counter.to_s][:epaisseur_lard],
                  poids_carcasse: params[counter.to_s][:poids_carcasse])
      counter += 1

      Coppa.create!(porc: porc) if porc.coppa.nil?
      Prisuttu.create!(porc: porc) if porc.prisuttu.nil?
      Lonzu.create!(porc: porc) if porc.lonzu.nil?
    end
    redirect_to abattage_path(@abattage)
  end

  def update_production
    porcs_abattage = @abattage.porcs.flat_map { |porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))
    count = @porcs.count
    counter = 0
      count.times do
        porc = Porc.find(params[counter.to_s][:id])
        porc.coppa.update(quantité: params[counter.to_s][:coppa][:quantité], numéro_lot: @abattage.id)
        porc.prisuttu.update(quantité: params[counter.to_s][:prisuttu][:quantité], numéro_lot: @abattage.id)
        porc.lonzu.update(quantité: params[counter.to_s][:lonzu][:quantité], numéro_lot: @abattage.id)
        counter += 1
      end
      redirect_to abattage_path(@abattage)
  end

  def update_coppa
    @abattage = Abattage.find(params[:abattage_id])
    ipg = params[:ipg]
    porc = Porc.find_by(boucle: ipg)

    @abattage.porcs.each do |p|
      p.coppa.update(poids: nil)
      p.coppa.update(date_mise_au_sel: nil)
      p.coppa.update(date_sortie_de_sel: nil)
      p.coppa.update(durée_fumage: nil)
      p.coppa.update(poids_sortie_sèche: nil)
      p.coppa.update(date_entrée_affinage: nil)
      p.coppa.update(date_sortie_affinage_vente: nil)
    end

    porc.coppa.update(poids: params[:poids])
    porc.coppa.update(date_mise_au_sel: params[:date_mise_au_sel])
    porc.coppa.update(date_sortie_de_sel: params[:date_sortie_de_sel])
    porc.coppa.update(durée_fumage: params[:durée_fumage])
    porc.coppa.update(poids_sortie_sèche: params[:poids_sortie_sèche])
    porc.coppa.update(date_entrée_affinage: params[:date_entrée_affinage])
    porc.coppa.update(date_sortie_affinage_vente: params[:date_sortie_affinage_vente])

    redirect_to abattage_path(@abattage)
  end

  def update_prisuttu
    @abattage = Abattage.find(params[:abattage_id])
    ipg = params[:ipg]
    porc = Porc.find_by(boucle: ipg)

    @abattage.porcs.each do |p|
      p.prisuttu.update(poids: nil)
      p.prisuttu.update(epaisseur_lard: nil)
      p.prisuttu.update(ph: nil)
      p.prisuttu.update(date_mise_au_sel: nil)
      p.prisuttu.update(date_sortie_de_sel: nil)
      p.prisuttu.update(durée_fumage: nil)
      p.prisuttu.update(poids_sortie_sèche: nil)
      p.prisuttu.update(date_entrée_affinage: nil)
      p.prisuttu.update(date_sortie_affinage_vente: nil)
    end

    porc.prisuttu.update(poids: params[:poids])
    porc.prisuttu.update(epaisseur_lard: params[:epaisseur_lard])
    porc.prisuttu.update(ph: params[:ph])
    porc.prisuttu.update(date_mise_au_sel: params[:date_mise_au_sel])
    porc.prisuttu.update(date_sortie_de_sel: params[:date_sortie_de_sel])
    porc.prisuttu.update(durée_fumage: params[:durée_fumage])
    porc.prisuttu.update(poids_sortie_sèche: params[:poids_sortie_sèche])
    porc.prisuttu.update(date_entrée_affinage: params[:date_entrée_affinage])
    porc.prisuttu.update(date_sortie_affinage_vente: params[:date_sortie_affinage_vente])

    redirect_to abattage_path(@abattage)
  end

  def update_lonzu
    @abattage = Abattage.find(params[:abattage_id])
    ipg = params[:ipg]
    porc = Porc.find_by(boucle: ipg)

    @abattage.porcs.each do |p|
      p.lonzu.update(poids: nil)
      p.lonzu.update(date_mise_au_sel: nil)
      p.lonzu.update(date_sortie_de_sel: nil)
      p.lonzu.update(durée_fumage: nil)
      p.lonzu.update(poids_sortie_sèche: nil)
      p.lonzu.update(date_entrée_affinage: nil)
      p.lonzu.update(date_sortie_affinage_vente: nil)
    end

    porc.lonzu.update(poids: params[:poids])
    porc.lonzu.update(date_mise_au_sel: params[:date_mise_au_sel])
    porc.lonzu.update(date_sortie_de_sel: params[:date_sortie_de_sel])
    porc.lonzu.update(durée_fumage: params[:durée_fumage])
    porc.lonzu.update(poids_sortie_sèche: params[:poids_sortie_sèche])
    porc.lonzu.update(date_entrée_affinage: params[:date_entrée_affinage])
    porc.lonzu.update(date_sortie_affinage_vente: params[:date_sortie_affinage_vente])

    redirect_to abattage_path(@abattage)
  end

  def download
    @abattage = Abattage.find(params[:abattage_id])
    porcs_abattage = @abattage.porcs.flat_map {|porc| porc }
    @porcs = Porc.where(id: porcs_abattage.pluck(:id))

    coppas_with_weight = @porcs.map(&:coppa).select do |coppa|
      coppa&.poids&.positive?
    end
    @coppa_temoin = coppas_with_weight.first

    lonzus_with_weight = @porcs.map(&:lonzu).select do |lonzu|
      lonzu&.poids&.positive?
    end
    @lonzu_temoin = lonzus_with_weight.first

    prisuttus_with_weight = @porcs.map(&:prisuttu).select do |prisuttu|
      prisuttu&.poids&.positive?
    end
    @prisuttu_temoin = prisuttus_with_weight.first

    render pdf: 'abattages/show',
           orientation: 'Landscape'
  end

  private

  def abattage_params
    params.require(:abattage).permit(:numéro_lot, :date, :lieu)
  end

  def set_abattage
    @abattage = Abattage.find(params[:id])
  end

  def set_abattage_id
    @abattage = Abattage.find(params[:abattage_id])
  end

  def etape_un_rempli?(porcs)
    porcs.all? do |porc|
      porc.poids_carcasse.present? &&
      porc.epaisseur_lard.present? &&
      porc.ph.present? &&
      porc.poids_carcasse != 0 &&
      porc.epaisseur_lard != 0 &&
      porc.ph != 0
    end
  end

  def etape_deux_rempli?(porcs)
    porcs.all? do |porc|
      !porc.coppa&.quantité.nil? &&
      !porc.lonzu&.quantité.nil? &&
      !porc.prisuttu&.quantité.nil?
    end
  end
end

app/views/abattages/edit.html.erb
<div class="container-global">
  <%= render "shared/head_bar" %>

  <div class="nav-container">
    <div class="head-info">
      <div>
        <h2 class="active">GESTION DU LOT N° <%= @abattage.numéro_lot %></h2>
      </div>

      <div class="elevage">
          <p><span style="color: gray; font-weight: 900;">Date</span> <%= @abattage.date.strftime("%d/%m/%Y") %></p>
          <p><span style="color: gray; font-weight: 900;">Lieu d'abattage</span> <%= @abattage.lieu %></p>
      </div>
    </div>
  </div>

  <div class="form-create-container" data-controller="checkable">
    <h2>Saisie des données</h2>
    <div style="width: 100px; height: 3px; background-color: gray; margin-bottom: 50px;"></div>
    <div class="formBloc" style="display: block;">
      <%= simple_form_for @abattage, url: abattage_update_abattage_path(@abattage), data: { turbo: "false", action: "keyup->checkable#validateForm" }, method: :patch do |fp| %>
        <table class="table">
          <thead>
            <tr>
              <th class="header">IPG</th>
              <th class="header">Poids carcasse (kg)</th>
              <th class="header">Epaisseur lard (cm)</th>
              <th class="header">pH</th>
              <th class="header"></th>
            </tr>
          </thead>
          <tbody>
            <% @porcs.each_with_index do |porc, index| %>
              <%= simple_fields_for porc do |p| %>
                <tr class="form-row" data-controller="aop" data-aop-target="bg">
                  <td class="boucle-porc" data-aop-target="porc"><%= current_user.EDE %><%= porc.boucle %></td>
                  <td class="form-input" >
                    <input type="number" step="0.01" name="<%= index %>[poids_carcasse]" id="poids-carcasse" value="<%= porc.poids_carcasse %>" data-action="keyup->aop#labelAop" data-aop-target="poids" data-checkable-target="checkable">
                  </td>
                  <td class="form-input">
                    <input type="number" step="0.01" name="<%= index %>[epaisseur_lard]" id="epaisseur-lard" value="<%= porc.epaisseur_lard %>" data-action="keyup->aop#labelAop" data-aop-target="lard" data-checkable-target="checkable">
                  </td>
                  <td class="form-input">
                    <input type="number" step="0.01" name="<%= index %>[ph]" id="ph" value="<%= porc.ph %>" data-action="keyup->aop#labelAop" data-aop-target="ph" data-checkable-target="checkable">
                  </td>
                  <td class="aop form-input text-end">
                  <input type="hidden" name="<%= index %>[id]" id="id" value="<%= porc.id %>">
                  <%= image_tag("aop.png", data: { aop_target: "eligible" }, class: "d-none") %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <div class="d-flex justify-content-between form-actions">
          <%= link_to "Annuler", abattage_path(@abattage), class: "annuler-button", data: { turbo: "false" } %>
          <div class="decoupe d-none" data-aop-target="decoupe" data-checkable-target="decoupe">
            <%= fp.button :submit, 'Valider', class: 'submit-button' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/abattages/new.html.erb
<div class="container-global">
  <%= render "shared/head_bar" %>
  <div class="form-create-container mt-5">
    <h2>NOUVEL ABATTAGE</h2>
    <div style="width: 100px; height: 3px; background-color: gray; margin-bottom: 50px;"></div>
    <%= simple_form_for :abattage, url: "/abattages", data: { turbo: "false" } do |f| %>
    <div class="formBloc">
      <div class="formGroupe">
        <%= f.input :numéro_lot, placeholder: "Ecrivez le numéro de lot" %>
      </div>
      <div class="formGroupe">
        <%= f.input :lieu, as: :select, collection: Abattage::ABATTOIRS %>
      </div>
      <div class="formGroupe">
        <%= f.input :date, as: :date %>
      </div>
      <div class="formGroupe mb-3" data-controller="select">
        <span style="color: black; font-weight: bold; font-size: 20px; transition: 0.4s ease-out">Porc abattus</span>
        <div id="list-porc" class="d-flex justify-content-start" data-select-target="list">
          <input type="hidden" name="porc_ids" id="porc-ids-input" value="">
        </div>
        <select data-select-target="select" data-action="change->select#updateList">
          <option value="" selected>Selectionner les porcs</option>
          <% @porcs.each do |porc| %>
            <%= content_tag :option, porc[:boucle], value: porc[:id] %>
          <% end %>
        </select>
      </div>
      <div class="d-flex justify-content-between form-actions">
        <%= link_to "Annuler", porcs_path, class: "annuler-button" %>
        <%= f.button :submit, "Ajouter", data: { disable_with: "Create abattage" }, class: "submit-button" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/abattages/show.html.erb
<div class="container-global">
  <%= render "shared/head_bar" %>

  <div class="nav-container">
      <div class="head-info">
        <div>
          <h2 class="active">INFORMATIONS DU LOT N°<%= @abattage.numéro_lot %></h2>
        </div>
        <div class="elevage">
            <p><span style="color: gray; font-weight: 900;">Date</span> <%= @abattage.date.strftime("%d/%m/%Y") %></p>
            <p><span style="color: gray; font-weight: 900;">Lieu d'abattage</span> <%= @abattage.lieu %></p>
        </div>
      </div>
  </div>

  <div class="nav-button mt-5 mb-5">
    <div>
      <%= link_to "< Retour", porcs_path, class: "annuler-button", style: "color: white;" %>
    </div>
    <div class="button-action" id="pdf">
      <%= link_to "OBTENIR LE PDF", abattage_download_path(@abattage), target: '_blank', class: "button-custom" %>
    </div>
  </div>

  <h2>Gestion des informations des porcs</h2>
  <div class="list-etape">
      <%= link_to edit_abattage_path(@abattage), data: { turbo: "false" } do %>
        <div class="etape" style="<%= @etape_un_rempli ? 'background-color: #0089d8;' : '' %>">Saisir les données de l'abattage</div>
      <% end %>

      <%= link_to abattage_edit_produits_path(@abattage), data: { turbo: "false" } do %>
        <div class="etape" style="<%= @etape_deux_rempli ? 'background-color: #0089d8;' : '' %>">Saisir le nombre de produits</div>
      <% end %>
  </div>

  <div class="list-tableau mb-5">
    <div class="tableau-content">
      <table style="table">
          <thead>
            <tr>
              <td>IPG du porc</td>
              <td>Poids carcasse (kg)</td>
              <td>Epaisseur du lard (cm)</td>
              <td>pH</td>
              <td>Quantité coppa</td>
              <td>Quantité lonzu</td>
              <td>Quantité prisuttu</td>
            </tr>
          </thead>
          <tbody>
            <% @abattage.porcs.each do |porc|%>
              <tr class="form-row">
                <td class="boucle-porc" style="line-height: 0;">
                  <%= porc.user.EDE %><%= porc.boucle %>
                </td>
                <td class="form-input">
                  <%= porc&.poids_carcasse%>
                </td>
                <td class="form-input">
                  <%= porc&.epaisseur_lard%>
                </td>
                <td class="form-input">
                  <%= porc&.ph%>
                </td>
                <td class="form-input">
                  <%= porc&.coppa&.quantité%>
                </td>
                <td class="form-input">
                  <%= porc&.lonzu&.quantité%>
                </td>
                <td class="form-input">
                  <%= porc&.prisuttu&.quantité%>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>

  <h2>Gestion des produits témoin</h2>
  <div class="list-etape">
        <%= link_to abattage_edit_coppa_path(@abattage), data: { turbo: "false" } do %>
        <div class="etape" style="<%= @coppa_temoin ? 'background-color: #0089d8;' : '' %>">Saisir la Coppa témoin</div>
      <% end %>

      <%= link_to abattage_edit_lonzu_path(@abattage), data: { turbo: "false" } do %>
        <div class="etape" style="<%= @lonzu_temoin ? 'background-color: #0089d8;' : '' %>">Saisir le Lonzu témoin</div>
      <% end %>

      <%= link_to abattage_edit_prisuttu_path(@abattage), data: { turbo: "false" } do %>
        <div class="etape" style="<%= @prisuttu_temoin ? 'background-color: #0089d8;' : '' %>">Saisir le Prisuttu témoin </div>
      <% end %>
  </div>

  <div class="list-tableau mb-5">
    <div class="tableau-content">
      <table style="table">
        <thead>
          <tr>
            <td>Produit</td>
            <td>Poids</td>
            <td>Epaisseur du lard (cm)</td>
            <td>pH</td>
            <td>Date mise au sel</td>
            <td>Date sortie de sel</td>
            <td>Durée de fumage (jours)</td>
            <td>Poids sortie de sèche (kg)</td>
            <td>Date entrée affinage</td>
            <td>Date sortie affinage vente</td>
          </tr>
        </thead>
        <tbody>
              <tr>
                <th>Coppa</th>
                <td class="form-input"><%= @coppa_temoin&.poids ? @coppa_temoin&.poids : 0 %></td>
                <td class="form-input">N/A</td>
                <td class="form-input">N/A</td>
                <td class="form-input"><%= @coppa_temoin&.date_mise_au_sel&.strftime("%d/%m/%Y") ? @coppa_temoin&.date_mise_au_sel&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @coppa_temoin&.date_sortie_de_sel&.strftime("%d/%m/%Y") ? @coppa_temoin&.date_sortie_de_sel&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @coppa_temoin&.durée_fumage ? @coppa_temoin&.durée_fumage : 0 %></td>
                <td class="form-input"><%= @coppa_temoin&.poids_sortie_sèche ? @coppa_temoin&.poids_sortie_sèche : 0 %></td>
                <td class="form-input"><%= @coppa_temoin&.date_entrée_affinage&.strftime("%d/%m/%Y") ? @coppa_temoin&.date_entrée_affinage&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @coppa_temoin&.date_sortie_affinage_vente&.strftime("%d/%m/%Y") ? @coppa_temoin&.date_sortie_affinage_vente&.strftime("%d/%m/%Y") : "null" %></td>
              </tr>

              <tr>
                <th>Lonzu</th>
                <td class="form-input"><%= @lonzu_temoin&.poids ? @lonzu_temoin&.poids : 0 %></td>
                <td class="form-input">N/A</td>
                <td class="form-input">N/A</td>
                <td class="form-input"><%= @lonzu_temoin&.date_mise_au_sel&.strftime("%d/%m/%Y") ? @lonzu_temoin&.date_mise_au_sel&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @lonzu_temoin&.date_sortie_de_sel&.strftime("%d/%m/%Y") ? @lonzu_temoin&.date_sortie_de_sel&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @lonzu_temoin&.durée_fumage ? @lonzu_temoin&.durée_fumage : 0 %></td>
                <td class="form-input"><%= @lonzu_temoin&.poids_sortie_sèche ? @lonzu_temoin&.poids_sortie_sèche : 0 %></td>
                <td class="form-input"><%= @lonzu_temoin&.date_entrée_affinage&.strftime("%d/%m/%Y") ? @lonzu_temoin&.date_entrée_affinage&.strftime("%d/%m/%Y") : "null"%></td>
                <td class="form-input"><%= @lonzu_temoin&.date_sortie_affinage_vente&.strftime("%d/%m/%Y") ? @lonzu_temoin&.date_sortie_affinage_vente&.strftime("%d/%m/%Y") : "null" %></td>
              </tr>

              <tr>
                <th>Prisuttu</th>
                <td class="form-input"><%= @prisuttu_temoin&.poids ? @prisuttu_temoin&.poids : 0 %></td>
                <td class="form-input"><%= @prisuttu_temoin&.epaisseur_lard ? @prisuttu_temoin&.epaisseur_lard : 0 %></td>
                <td class="form-input"><%= @prisuttu_temoin&.ph ? @prisuttu_temoin&.ph : 0 %></td>
                <td class="form-input"><%= @prisuttu_temoin&.date_mise_au_sel&.strftime("%d/%m/%Y") ? @prisuttu_temoin&.date_mise_au_sel&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @prisuttu_temoin&.date_sortie_de_sel&.strftime("%d/%m/%Y") ? @prisuttu_temoin&.date_sortie_de_sel&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @prisuttu_temoin&.durée_fumage ? @prisuttu_temoin&.durée_fumage : 0 %></td>
                <td class="form-input"><%= @prisuttu_temoin&.poids_sortie_sèche ? @prisuttu_temoin&.poids_sortie_sèche : 0 %></td>
                <td class="form-input"><%= @prisuttu_temoin&.date_entrée_affinage&.strftime("%d/%m/%Y") ? @prisuttu_temoin&.date_entrée_affinage&.strftime("%d/%m/%Y") : "null" %></td>
                <td class="form-input"><%= @prisuttu_temoin&.date_sortie_affinage_vente&.strftime("%d/%m/%Y") ? @prisuttu_temoin&.date_sortie_affinage_vente&.strftime("%d/%m/%Y") : "null" %></td>
              </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>