config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "porcs#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :porcs, only: [:index, :new, :create, :show, :edit, :update, :gestion] do
    get "gestion", to: "porcs#gestion"
    resources :prisuttus, only: [:new, :create, :edit, :update]
    resources :lonzus, only: [:new, :create, :edit, :update]
    resources :coppas, only: [:new, :create, :edit, :update]
  end

  resources :abattages, except: [:index, :update] do
    get "edit_produits", to: "abattages#edit_produits"
    get "edit_coppa", to: "abattages#edit_coppa"
    get "edit_lonzu", to: "abattages#edit_lonzu"
    get "edit_prisuttu", to: "abattages#edit_prisuttu"
    get "/dashboard", to: "abattages#dashboard"
    get "download", to: "abattages#download"
    get "preview", to: "abattages#preview"
    patch "update_abattage", to: "abattages#update_abattage", as: :update_abattage
    patch "/update_production", to: "abattages#update_production", as: :update_production
    patch "/update_produits", to: "abattages#update_produits", as: :update_produits
    patch "/update_coppa", to: "abattages#update_coppa", as: :update_coppa
    patch "/update_lonzu", to: "abattages#update_lonzu", as: :update_lonzu
    patch "/update_prisuttu", to: "abattages#update_prisuttu", as: :update_prisuttu
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/porc.rb
class Porc < ApplicationRecord
  belongs_to :user
  belongs_to :abattage, optional: true
  has_one :prisuttu, dependent: :destroy
  has_one :lonzu, dependent: :destroy
  has_one :coppa, dependent: :destroy
  accepts_nested_attributes_for :prisuttu, :coppa
  validates :user, :boucle, :boucle_mère, :boucle_père, :date_de_naissance, :sexe, presence: true
  validates :sexe, inclusion: { in: %w[mâle femelle]}
end

app/controllers/porcs_controller.rb
class PorcsController < ApplicationController
  before_action :set_porc, only: [:edit, :show, :update]

  def index
    @ipg = params[:ipg]
    @lot = params[:lot]

    if @ipg.present?
      @porcs = Porc.where("boucle ILIKE ?", "%#{@ipg}%")
    else
      @porcs = Porc.where(décès: false, abattu: false)
    end

    if @lot.present?
      @abattages = Abattage.where(numéro_lot: @lot.to_i)
    else
      @abattages = Abattage.all
    end
  end

  def new
    @porc = Porc.new
  end

  def create
    @porc = Porc.new(porc_params)
    # @porc.build_prisuttu
    # @porc.build_lonzu
    # @porc.build_coppa
    @porc.user = current_user
    if @porc.save!
      redirect_to porcs_path
    else
      render :new
    end
  end

  def show;
  end

  def gestion
    @porc = Porc.find(params[:porc_id])
    @selected_value_mere = @porc.boucle_mère
    @selected_value_pere = @porc.boucle_père
  end

  def edit
    @selected_value_mere = @porc.boucle_mère
    @selected_value_pere = @porc.boucle_père
  end

  def update
    if @porc.update(porc_params)
      if porc_params[:ph]
        render :edit
      else
        if porc_params[:décès] == "0"
          @porc.update(date_décès: "")
        end
        redirect_to porc_path(@porc)
      end
    else
      render :edit
    end
  end

  private

  def porc_params
    params.require(:porc).permit(:boucle, :boucle_mère, :boucle_père, :date_de_naissance, :sexe, :poids, :vermifuge_2_mois, :vermifuge_6_mois, :vermifuge_12_mois, :décès, :date_décès, :poids_carcasse, :epaisseur_lard, :ph, :coppa)
  end

  def set_porc
    @porc = Porc.find(params[:id])
  end
end

app/views/porcs/edit.html.erb
<div class="container-global">
  <%= render "shared/head_bar" %>
  <div class="form-create-container mt-3">
    <h2>MODIFICATION DU PORC <%=@porc.user.EDE%><%=@porc.boucle%></h2>
    <div style="width: 100px; height: 3px; background-color: gray; margin-bottom: 50px;"></div>
      <%= simple_form_for @porc do |f| %>
        <div class="formBloc">
          <div class="formGroupe">
            <%= f.input :boucle %>
          </div>
          <div class="formGroupe">
            <%= f.input :date_de_naissance, as: :date %>
          </div>
          <div class="formGroupe">
            <%= f.input :boucle_mère, collection: Porc.where(sexe: "femelle").pluck(:boucle), selected: @selected_value_mere %>
          </div>
          <div class="formGroupe">
            <%= f.input :boucle_père, collection: Porc.where(sexe: "mâle").pluck(:boucle), selected: @selected_value_pere %>
          </div>
          <div>
            <span style="color: black; font-weight: bold; font-size: 20px; transition: 0.4s ease-out">Sexe</span>
            <%= f.input :sexe,
                              as: :radio_buttons,
                              input_html: { class: "tag-selector" },
                              item_wrapper_class: 'tag-item',
                              collection: [['mâle', 'mâle'], ['femelle', 'femelle']] %>
          </div>
          <div class="d-flex justify-content-between form-actions">
            <%= link_to "Annuler", porc_path(@porc), class: "annuler-button" %>
            <%= f.button :submit, "Valider", class: "submit-button" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/porcs/gestion.html.erb
<div class="container-global">
  <%= render "shared/head_bar" %>
  <div class="form-create-container mt-3">
    <h2>GESTION DU PORC <%=@porc.user.EDE%><%=@porc.boucle%></h2>
    <div style="width: 100px; height: 3px; background-color: gray; margin-bottom: 50px;"></div>
    <%= simple_form_for @porc do |f| %>
      <div class="gestion-container">

        <div class="formBloc left">
          <div class="formGroupe">
            <%= f.input :poids, placeholder: "Renseigner le poids à 2 mois" %>
          </div>
          <div class="vermifuge mb-3">
            <span style="color: black; font-weight: bold; font-size: 20px; transition: 0.4s ease-out">Vermifuge</span>
            <%= f.input :vermifuge_2_mois, as: :boolean, label: "Vermifuge à 2 mois", input_html: { class: "form-check-input toggle", id: "porc_vermifuge_2_mois" } %>
            <%= f.input :vermifuge_6_mois, as: :boolean, label: "Vermifuge à 6 mois", input_html: { class: "form-check-input toggle", id: "porc_vermifuge_6_mois" } %>
            <%= f.input :vermifuge_12_mois, as: :boolean, label: "Vermifuge à 12 mois", input_html: { class: "form-check-input toggle", id: "porc_vermifuge_12_mois" } %>
          </div>
        </div>

        <div class="separator"></div>

        <div class="right" data-controller="deces">
          <span style="color: black; font-weight: bold; font-size: 20px; transition: 0.4s ease-out">Décès sur exploitation</span>
            <%= f.input :décès, as: :boolean, label: "Porc décedé ?", input_html: { class: "form-check-input toggle", id: "deces", data: { action: "click->deces#toggleDateDeces", deces_target: "checkbox" } } %>
          <div class="formBloc d-deces d-none" data-deces-target="block">
            <div class="formGroupe">
              <%= f.input :date_décès, as: :date %>
            </div>
          </div>
        </div>

      </div>
      <div class="d-flex justify-content-between form-actions">
        <%= link_to "Annuler", porc_path(@porc), class: "annuler-button" %>
        <%= f.button :submit, "Valider", class: "submit-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/porcs/index.html.erb
<div class="container-global">
  <%= render "shared/head_bar" %>

  <div data-controller="grid">

    <%= render "shared/navbar" %>

    <% @porcs.each do |porc| %>
      <% if !porc.vermifuge_2_mois && !porc.poids && porc.boucle == "00013" %>
        <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
          <span><strong> Rappel:</strong> Pesée et vermifuge pour le porc <%= porc.user.EDE %><%= porc.boucle %>   </span>
          <a data-bs-dismiss="alert" aria-label="Close">
            <i class="fas fa-times"></i>
          </a>
        </div>
      <% end %>
    <% end %>

    <% if @ipg.present? && @porcs.empty? %>
      <div class="elevage-container enable" data-grid-target="grid">
        Aucune recherche correspondante..
      </div>
    <% else %>
      <div class="elevage-container enable" data-grid-target="grid">
        <% @porcs.each do |porc| %>
          <%= link_to porc_path(porc) do %>
            <div class="elevage d-flex flex-column">
              <span style="color: gray;">N° IPG</span><%= porc.user.EDE %><%= porc.boucle %>
              <span style="color: gray;">Né(e) le</span> <%= porc.date_de_naissance.strftime("%d/%m/%Y") %>
              <span style="color: gray;">Sexe</span> <%= porc.sexe.capitalize %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if @lot.present? && !@abattages.map { |abattage| abattage.numéro_lot.to_i }.include?(@lot.to_i) %>
      <div class="elevage-container enable" data-grid-target="grid">
        Aucune recherche correspondante..
      </div>
    <% else %>
      <div class="production-container" data-grid-target="grid">
        <% @abattages.each do |abattage| %>
          <%= link_to abattage_path(abattage) do %>
            <div class="productions">
              <p><span style="color: gray">Lot</span>&nbsp;&nbsp; <%= abattage.numéro_lot %></p>
              <p><span style="color: gray">Lieu</span>&nbsp;&nbsp; <%= abattage.lieu %></p>
              <p><span style="color: gray">Date abattoir</span>&nbsp;&nbsp; <%= abattage.date.strftime("%d/%m/%Y") %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/porcs/new.html.erb
p<div class="container-global">
  <%= render "shared/head_bar" %>
  <div class="form-create-container mt-3">
    <h2>AJOUTER UN NOUVEL ANIMAL</h2>
    <div style="width: 100px; height: 3px; background-color: gray; margin-bottom: 50px;"></div>
      <%= simple_form_for @porc do |f| %>
        <div class="formBloc">
          <div class="formGroupe">
            <%= f.input :boucle %>
          </div>
          <div class="formGroupe">
            <%= f.input :date_de_naissance, as: :date %>
          </div>
          <div class="formGroupe">
            <%= f.input :boucle_mère, collection: Porc.where(sexe: "femelle").pluck(:boucle), selected: @selected_value_mere %>
          </div>
          <div class="formGroupe">
            <%= f.input :boucle_père, collection: Porc.where(sexe: "mâle").pluck(:boucle), selected: @selected_value_pere %>
          </div>
          <div>
            <span style="color: black; font-weight: bold; font-size: 20px; transition: 0.4s ease-out">Sexe</span>
            <%= f.input :sexe,
                              as: :radio_buttons,
                              input_html: { class: "tag-selector" },
                              item_wrapper_class: 'tag-item',
                              collection: [['mâle', 'mâle'], ['femelle', 'femelle']] %>
          </div>
          <div class="d-flex justify-content-between form-actions">
            <%= link_to "Annuler", porcs_path, class: "annuler-button" %>
            <%= f.button :submit, "Ajouter", class: "submit-button" %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/porcs/show.html.erb
<div class="container-global">
  <%= render "shared/head_bar" %>

  <h1>Informations du porc <%=@porc.user.EDE%><%=@porc.boucle%></h1>
  <div class="nav-button">
    <div>
      <%= link_to "< Retour", porcs_path, class: "annuler-button", style: "color: white;" %>
    </div>
    <div class="button-action">
      <%= link_to "MODIFIER", edit_porc_path(@porc), class: "button-custom" %>
      <%= link_to "GESTION ANIMAL", porc_gestion_path(@porc), class: "button-custom" %>
    </div>
  </div>

  <div class="view-info">
    <div class="grid-container">
      <div class="card">
        <h4>Informations générales</h4>
        <div class="infos-porc">
          <p><span style="color: gray; font-weight: 900;">N° IPG</span> <%=@porc.user.EDE%><%=@porc.boucle%></p>
          <p><span style="color: gray; font-weight: 900;">Né.e le</span> <%= @porc.date_de_naissance.strftime("%d/%m/%Y") %></p>
          <p><span style="color: gray; font-weight: 900;">Sexe</span> <%= @porc.sexe %></p>
          <p><span style="color: gray; font-weight: 900;">Poids à 2 mois</span> <% if @porc.poids.nil? %>Aucun poids renseigné<% else %><%= @porc.poids %>kg<% end %></p>
        </div>
      </div>

      <div class="card">
        <h4>Informations sur le vermifuge</h4>
        <div class="vermifuges-container">
          <div class="vermifuges">
            <% if @porc.vermifuge_2_mois %>
              <i class="fa-solid fa-check"></i>
            <% else %>
              <i class="fa-solid fa-x"></i>
            <% end %>
            <span style="color: gray; font-weight: 900;">Vermifuge à 2 mois</span>
          </div>
          <div class="vermifuges">
            <% if @porc.vermifuge_6_mois %>
              <i class="fa-solid fa-check"></i>
            <% else %>
              <i class="fa-solid fa-x"></i>
            <% end %>
            <span style="color: gray; font-weight: 900;">Vermifuge à 6 mois</span>
          </div>
          <div class="vermifuges">
            <% if @porc.vermifuge_12_mois %>
              <i class="fa-solid fa-check"></i>
            <% else %>
              <i class="fa-solid fa-x"></i>
            <% end %>
            <span style="color: gray; font-weight: 900;">Vermifuge à 12 mois</span>
          </div>
        </div>
      </div>

      <div class="card">
        <h4>Informations sur la mère</h4>
        <div class="infos-mère">
          <div>
            <p><span style="color: gray; font-weight: 900;">N° IPG</span> <%=@porc.user.EDE%><%=@porc.boucle_mère%></p>
            <p><span style="color: gray; font-weight: 900;">Née le</span>
            <% if @porc.boucle_mère %>
             <%= Porc.find_by("boucle like ?", @porc.boucle_mère)&.date_de_naissance.strftime("%d/%m/%Y")%>
             <% else %>
            <p>T'es orphelin mec</p>
            <% end %>
            </p>
          </div>
        </div>
      </div>

      <div class="card">
        <h4>Informations sur le père</h4>
        <div class="infos-père">
            <p><span style="color: gray; font-weight: 900;">N° IPG</span> <%=@porc.user.EDE%><%=@porc.boucle_père%></p>
            <p><span style="color: gray; font-weight: 900;">Né le</span> <%= Porc.find_by("boucle like ?", @porc.boucle_père)&.date_de_naissance.strftime("%d/%m/%Y")%></p>
        </div>
      </div>
    </div>

    <% if @porc.décès %>
      <div class="deces-container">
        <div class="card deces">
          <% if @porc.décès %>
            <h4>Décès sur exploitation</h4>
            <div class="décès">
              <span style="color: gray; font-weight: 900;">Décédé le</span> <%= @porc.date_décès %>
            </div>
            <% elsif @porc.abattu %>
            <h4>Date de passage en abattoire</h4>
            <div class="décès">
              <span style="color: gray; font-weight: 900;">Envoyé à l'abattoir le</span> <%= @porc.abattage.date %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>